font:
  normal:
    family: Source Code Pro
    style: Regular
  bold:
    family: Source Code Pro
    style: Bold
  italic:
    family: Source Code Pro
    style: Italic

  size: 8

key_bindings:
  - { key: NumpadEquals,   mods: Control, action:
ResetFontSize                }
  - { key: NumpadAdd,      mods: Control, action:
IncreaseFontSize             }
  - { key: NumpadSubtract, mods: Control, action:
DecreaseFontSize          }
